steps:

- name: 'gcr.io/cloud-builders/npm'
  env: ['CI=true']
  args: ['install', '--quiet']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'lint']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test:unit']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']